name: Generate Snake & Pac-Man Animations

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate_animations:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Generate Snake Animation
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      # Generate Pac-Man Animation (Black Theme)
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          theme: black  # Black theme
          background: transparent
          pacman_color: "#FFD700"  # Gold Pac-Man
          ghost_color: "#FF4500,#1E90FF,#9932CC,#32CD32"  # Red, Blue, Purple, Green Ghosts
          speed: 2
          frame_duration: 60

      # Deploy both animations to the `output` branch
      - name: Commit and Push Updates
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Success Message
        run: echo "Snake & Pac-Man animations updated successfully!"
