name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Runs exactly every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate_snake_animation:
    name: Generate & Deploy Snake Animation
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Cache Snake SVG for Faster Builds
        uses: actions/cache@v3
        with:
          path: dist/snake.svg
          key: snake-${{ github.run_id }}
          restore-keys: snake-

      - name: Commit and Push Updates
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Success Message
        run: echo "Snake animation updated successfully!"
